name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      checks: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Run Tests
        run: dotnet test Tests/Tests.csproj --configuration Release --logger "trx;LogFileName=test-results.trx"

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Unit Test Results
          path: "**/test-results.trx"
          reporter: dotnet-trx

  deploy:
    name: Deploy UPM branch
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build upm branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Create and switch to upm branch from main
          git checkout -b upm
          
          # Remove unrelated files for UPM-version
          rm -rf Tests
          rm -rf Tests.meta
          rm -rf .github
          rm -rf .idea
          rm -rf Documentation
          
          # Add and commit changes
          git add -A
          git commit -m "Update UPM branch - $(date)"
          
          # Push the upm branch
          git push -f origin upm
