name: Deploy UPM branch

on:
  push:
    branches:
      - main

jobs:
  deploy-upm:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build upm branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Create and switch to upm branch from main
          git checkout -b upm
          
          # Remove unrelated files for UPM-version
          rm -rf Tests
          rm -rf Tests.meta
          rm -rf .github
          rm -rf .idea
          rm -rf Documentation
          
          # Add and commit changes
          git add -A
          git commit -m "Update UPM branch - $(date)"
          
          # Push the upm branch
          git push -f origin upm
