name: Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit-test-job:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # Or specify the version your project uses

      - name: Run Tests
        run: dotnet test Tests/Tests.csproj --configuration Release --collect:"XPlat Code Coverage"

      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-Action@5.2.4
        with:
          reports: 'Tests/TestResults/**/coverage.cobertura.xml'
          targetdir: 'coveragereport'
          reporttypes: 'MarkdownSummary;Badges'

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: coveragereport
